In [136]:
import pandas as pd
import numpy as np
#基于numpy

In [137]:
#Series：一维
#DateFrame：二维

 # Series

## 基本

In [138]:
s=pd.Series([1,2,3,4,5,6])
print(s)
#第一列索引，第二列数据

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [139]:
s=pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'])
print(s)
#index自定义索引

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [140]:
s=pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'],name='a')
print(s)
#name：描述

a    1
b    2
c    3
d    4
e    5
f    6
Name: a, dtype: int64

In [141]:
s=pd.Series({'a':1,'b':2,'c':3,'d':4,'e':5})
#可以通过字典来创建
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [142]:
s=pd.Series(s,index=['a','c'])
#在s中截取
print(s)

a    1
c    3
dtype: int64

## 属性

In [143]:
s=pd.Series([1,2,3],index=['a','b','c'],name='a')
print(s)
print(s.index) #索引
print(s.values) #元素
print(s.shape) #形状
print(s.ndim) #维度
print(s.size) #元素个数
print(s.dtype) #元素类型
print(s.name) #名字

a    1
b    2
c    3
Name: a, dtype: int64
Index(['a', 'b', 'c'], dtype='str')
[1 2 3]
(3,)
1
3
int64
a

In [144]:
s=pd.Series([1,2,3],index=['a','b','c'],name='a')
print(s)
print(s.loc['a']) #显式索引
print(s.iloc[1]) #隐式索引
print(s.loc['a':'b']) #显式切片
print(s.iloc[0:2]) #隐式切片
print(s.at['a']) #显式索引，不支持切片
print(s.iat[0]) #隐式索引，不支持切片

a    1
b    2
c    3
Name: a, dtype: int64
1
2
a    1
b    2
Name: a, dtype: int64
a    1
b    2
Name: a, dtype: int64
1
1

## 访问数据

In [145]:
s=pd.Series([1,2,3],index=['a','b','c'],name='a')
print(s['a'])  #直接访问
print(s[s<3])  #筛选

1
a    1
b    2
Name: a, dtype: int64

In [146]:
s=pd.Series([1,2,3,4,5,6,7,8,9],index=['a','b','c','d','e','f','g','h','i',],name='a')
print(s)
print(s.head()) #返回前五行
print(s.tail()) #返回后五行
#head/tail的括号中写数字则返回前几行或后几行

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
Name: a, dtype: int64
a    1
b    2
c    3
d    4
e    5
Name: a, dtype: int64
e    5
f    6
g    7
h    8
i    9
Name: a, dtype: int64

## 常用方法

In [147]:
s=pd.Series([1,2,3,4,5,6,7,8,9],index=['a','b','c','d','e','f','g','h','i',],name='a')
print(s)
print(s.isin([1,4,7]))   #判断几个值是否包含
print(s.isna())  #判断是不是缺失值
#sun()求和；mean()平均值；min()最小值；max()最大值
#var()方差；std()标准差；median()中位数；mode()众数；quantile()分位数

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
Name: a, dtype: int64
a     True
b    False
c    False
d     True
e    False
f    False
g     True
h    False
i    False
Name: a, dtype: bool
a    False
b    False
c    False
d    False
e    False
f    False
g    False
h    False
i    False
Name: a, dtype: bool

In [148]:
s=pd.Series([1,2,3,4,5,6,7,8,9],index=['a','b','c','d','e','f','g','h','i',],name='a')
print(s)
print(s.describe()) #返回常见统计数据

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
Name: a, dtype: int64
count    9.000000
mean     5.000000
std      2.738613
min      1.000000
25%      3.000000
50%      5.000000
75%      7.000000
max      9.000000
Name: a, dtype: float64

In [149]:
s=pd.Series([1,2,3,4,5,6,7,8,9],index=['a','b','c','d','e','f','g','h','i',],name='a')
print(s)
print(s.value_counts()) #每个唯一值出现次数
print(s.count())     #非缺失值数量

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
Name: a, dtype: int64
a
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
9    1
Name: count, dtype: int64
9

In [150]:
print(s)
print(s.nunique()) #唯一值个数
print(s.unique()) #返回去重后数组
print(s.keys()) #获取索引

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
Name: a, dtype: int64
9
[1 2 3 4 5 6 7 8 9]
Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='str')

In [151]:
s=pd.Series([1,1,3,5,5,6,7,7,9],index=['a','b','c','d','e','f','g','h','i',],name='a')
print(s)
print(s.drop_duplicates()) #去除重复项

a    1
b    1
c    3
d    5
e    5
f    6
g    7
h    7
i    9
Name: a, dtype: int64
a    1
c    3
d    5
f    6
g    7
i    9
Name: a, dtype: int64

In [152]:
print(s.sample())  #随机抽一个元素
print(s.sort_index()) #按索引顺序排序
print(s.sort_values()) #按值排序

a    1
Name: a, dtype: int64
a    1
b    1
c    3
d    5
e    5
f    6
g    7
h    7
i    9
Name: a, dtype: int64
a    1
b    1
c    3
d    5
e    5
f    6
g    7
h    7
i    9
Name: a, dtype: int64

# DateFrame

## 创建

In [153]:
s1=pd.Series([1,2,3,4,5,6,6,6])
s2=pd.Series([7,8,9,10,11,11,12,12])
s=pd.DataFrame({'一':s1,'二':s2})
s

   一   二
0  1   7
1  2   8
2  3   9
3  4  10
4  5  11
5  6  11
6  6  12
7  6  12

In [154]:
s=pd.DataFrame(
    {
        'name':['a','b','c'],
        'age':[10,11,12],
        'score':['1.1','1.2','1.3'],
        'bool':[True,False,True]
    },index=[1,2,3],columns=['name','score','age','bool']
)
#字典创建
#index索引；columns指定列的顺序，
s

  name score  age   bool
1    a   1.1   10   True
2    b   1.2   11  False
3    c   1.3   12   True

## 属性

In [155]:
s=pd.DataFrame(
    {
        'name':['a','b','c'],
        'age':[10,11,12],
        'score':['1.1','1.2','1.3'],
        'bool':[True,False,True]
    },index=[1,2,3],columns=['name','score','age','bool']
)
print(s.index) #行索引
print(s.columns) #列标签
print(s.values) #值
print(s.ndim) #维度
print(s.shape) #形状
print(s.dtypes) #元素类型
print(s.size) #元素个数

Index([1, 2, 3], dtype='int64')
Index(['name', 'score', 'age', 'bool'], dtype='str')
[['a' '1.1' 10 True]
 ['b' '1.2' 11 False]
 ['c' '1.3' 12 True]]
2
(3, 4)
name       str
score      str
age      int64
bool      bool
dtype: object
12

In [156]:
print(s.T) #转置
#转置会让行索引和列标签互换

          1      2     3
name      a      b     c
score   1.1    1.2   1.3
age      10     11    12
bool   True  False  True

In [157]:
print(s.loc[1])  #显式索引，获取行
print(s.iloc[1]) #隐式索引，获取行
print(s.loc[:,'name']) #显式索引，获取列
print(s.iloc[:,0])  #隐式索引，获取列

name        a
score     1.1
age        10
bool     True
Name: 1, dtype: object
name         b
score      1.2
age         11
bool     False
Name: 2, dtype: object
1    a
2    b
3    c
Name: name, dtype: str
1    a
2    b
3    c
Name: name, dtype: str

In [158]:
print(s.at[1,'name']) #显式索引，获取单个元素
print(s.iat[0,0]) #隐式索引，获取单个元素
#获取单个元素用loc也可以

a
a

## 访问数据

In [159]:
s=pd.DataFrame(
    {
        'name':['a','b','c'],
        'age':[10,11,12],
        'score':['1.1','1.2','1.3'],
        'bool':[True,False,True]
    },index=[1,2,3],columns=['name','score','age','bool']
)
s

  name score  age   bool
1    a   1.1   10   True
2    b   1.2   11  False
3    c   1.3   12   True

In [160]:
print(s['name'])#和loc和at差不多
print(s.name)

1    a
2    b
3    c
Name: name, dtype: str
1    a
2    b
3    c
Name: name, dtype: str

In [161]:
#查看部分数据
print(s.head(2)) #头两行
print(s.tail(2)) #尾两行

  name score  age   bool
1    a   1.1   10   True
2    b   1.2   11  False
  name score  age   bool
2    b   1.2   11  False
3    c   1.3   12   True

In [162]:
s.age>11  #布尔索引

1    False
2    False
3     True
Name: age, dtype: bool

In [163]:
s[s.age>11]

  name score  age  bool
3    c   1.3   12  True

In [164]:
s[(s.age>10) & (s.age<12)]

  name score  age   bool
2    b   1.2   11  False

In [165]:
s.sample(2)  #随机取，括号内写几取几条

  name score  age   bool
3    c   1.3   12   True
2    b   1.2   11  False

## 常用方法

In [166]:
#head()；tail()
s=pd.DataFrame(
    {
        'name':['a','b','c'],
        'age':[10,11,12],
        'score':['1.1','1.2','1.3'],
        'bool':[True,False,True]
    },index=[1,2,3],columns=['name','score','age','bool']
)
s

  name score  age   bool
1    a   1.1   10   True
2    b   1.2   11  False
3    c   1.3   12   True

In [167]:
print(s.isin([11])) #查看某个元素在不在
print(s.isna())  #查有没有空缺

    name  score    age   bool
1  False  False  False  False
2  False  False   True  False
3  False  False  False  False
    name  score    age   bool
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False

In [168]:
print(s.sum())  #各列求和
print(s['age'].sum()) #指定列求和

name           abc
score    1.11.21.3
age             33
bool             2
dtype: object
33

In [169]:
# print(s.age.max()) #大
# print(s.age.min()) #小
# print(s.age.mean()) #平均
# print(s.age.median())#中位
# print(s.age.mode()) #众数
# print(s.age.std()) #标准差
# print(s.age.var()) #方差
print(s.describe()) #普遍信息

        age
count   3.0
mean   11.0
std     1.0
min    10.0
25%    10.5
50%    11.0
75%    11.5
max    12.0

In [170]:
print(s.count())  #每列非缺失值个数

name     3
score    3
age      3
bool     3
dtype: int64

In [171]:
print(s.value_counts()) #每条信息出现次数
print(s.drop_duplicates()) #去重
print(s.duplicated(subset='age')) #检查是否重复(subset指定某一列

name  score  age  bool
a     1.1    10   True     1
b     1.2    11   False    1
c     1.3    12   True     1
Name: count, dtype: int64
  name score  age   bool
1    a   1.1   10   True
2    b   1.2   11  False
3    c   1.3   12   True
1    False
2    False
3    False
dtype: bool

In [172]:
print(s.replace(12,30))  #替换某个值

  name score  age   bool
1    a   1.1   10   True
2    b   1.2   11  False
3    c   1.3   30   True

In [173]:
print(s.cumsum()) #累计和

  name      score  age  bool
1    a        1.1   10     1
2   ab     1.11.2   21     1
3  abc  1.11.21.3   33     2

In [174]:
print(s.sort_index())  #按索引排序
print(s.sort_values(by=['age','score'],ascending=[True,False]))
#按值排序
#by=必须写，指定排序的列，写多个按从前往后排（前一个相同再看下一个）
#ascending=指定正逆(True从小到大，False从大到小），by写了几个这也要写几个

  name score  age   bool
1    a   1.1   10   True
2    b   1.2   11  False
3    c   1.3   12   True
  name score  age   bool
1    a   1.1   10   True
2    b   1.2   11  False
3    c   1.3   12   True

In [175]:
print(s.nlargest(2,['age'])) #取age列里最大的两个
print(s.nsmallest(2,['age'])) #取age列里最小的两个

  name score  age   bool
3    c   1.3   12   True
2    b   1.2   11  False
  name score  age   bool
1    a   1.1   10   True
2    b   1.2   11  False

# 数据分析

In [176]:
#收集，清洗，分析

## 读取输出

In [177]:
s=pd.read_csv('war.csv')  #读入
s.head(20)

,Conflict_Name,Conflict_Type,Region,Start_Year,End_Year,Status,Primary_Country,Pre_War_Unemployment_%,During_War_Unemployment_%,Unemployment_Spike_Percentage_Points,Most_Affected_Sector,Youth_Unemployment_Change_%,Pre_War_Poverty_Rate_%,During_War_Poverty_Rate_%,Extreme_Poverty_Rate_%,Food_Insecurity_Rate_%,Households_Fallen_Into_Poverty_Estimate,GDP_Change_%,Inflation_Rate_%,Currency_Devaluation_%,Cost_of_War_USD,Estimated_Reconstruction_Cost_USD,Informal_Economy_Size_Pre_War_%,Informal_Economy_Size_During_War_%,Black_Market_Activity_Level,Primary_Black_Market_Goods,Currency_Black_Market_Rate_Gap_%,War_Profiteering_Documented
0,WWII (Japan),World War,East Asia,1939,1945,Resolved,Japan,7.49,21.78,14.29,Construction,19.90,19.97,28.67,10.39,15.00,38487,-36.86,97.41,170.33,106957216228,209054555175,15.50,27.09,High,food,10.50,No
1,Israel-Hamas War,Asymmetric War,Middle East,2023,2026,Ongoing,Palestine (Gaza),8.18,23.00,14.82,Tourism,19.92,8.49,18.93,8.45,12.92,166213,-64.99,73.68,41.97,304164881098,585915946162,11.95,34.76,Dominant,fuel,19.31,No
2,Syrian Civil War,Civil War,Middle East,2011,2026,Ongoing,Syria,12.70,36.46,23.76,Tourism,27.06,22.11,41.31,14.41,28.83,114129,-19.03,69.35,53.91,484822729254,1666739121273,38.18,90.00,Moderate,"water, weapons, currency",298.95,No
3,WWII (Germany),World War,Europe,1939,1945,Resolved,Germany,14.06,17.83,3.77,Construction,4.44,6.13,8.87,4.04,5.40,1916,-42.29,36.92,48.51,71321188262,250015887113,12.24,36.42,Moderate,"currency, medicine, weapons",15.44,No
4,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,Resolved,Afghanistan,5.38,5.98,0.59,Construction,0.85,22.67,23.27,14.16,12.33,4111,-43.84,52.62,31.32,156180178536,361238241031,31.89,74.86,Dominant,medicine,443.61,Yes
5,WWII (Germany),World War,Europe,1939,1945,Resolved,Germany,8.67,11.50,2.84,Construction,3.93,24.02,26.55,16.15,18.52,11867,-28.52,13.70,9.07,16683163657,51568093097,19.43,41.10,Dominant,"fuel, currency, water",18.15,Yes
6,WWII (Japan),World War,East Asia,1939,1945,Resolved,Japan,5.99,11.26,5.27,Tourism,7.39,10.72,13.64,5.67,7.70,137420,-41.17,93.39,122.24,403912637426,1510725456958,19.54,27.32,Moderate,"fuel, water, food",4.56,Yes
7,Israel-Hamas War,Asymmetric War,Middle East,2023,2026,Ongoing,Palestine (Gaza),8.13,42.10,33.97,Construction,49.07,5.17,34.31,16.02,20.20,42510,-68.44,89.58,114.50,351806460488,847527799087,39.15,90.00,Dominant,"currency, medicine",125.89,No
8,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,Resolved,Afghanistan,8.97,14.99,6.02,Energy,7.31,5.92,11.50,5.76,5.99,57268,-15.78,52.08,103.03,121785580484,387319415238,32.85,53.47,High,"water, fuel, food",364.11,Yes
9,Syrian Civil War,Civil War,Middle East,2011,2026,Ongoing,Syria,7.41,32.21,24.80,Manufacturing,33.57,18.39,32.36,20.52,20.33,13120,-13.39,59.92,90.86,9277326635,25793126375,16.79,39.66,Dominant,"water, weapons",3.49,No
10,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,Resolved,Afghanistan,11.29,20.72,9.43,Agriculture,13.90,8.44,15.40,5.32,13.40,10791,-34.70,89.51,115.87,121684293159,210849300968,36.92,90.00,Low,"currency, medicine",316.55,No
11,WWII (Germany),World War,Europe,1939,1945,Resolved,Germany,7.07,12.47,5.40,Agriculture,7.50,27.43,33.48,20.49,25.34,66986,-8.79,93.38,131.63,5589328756,9801887666,29.91,36.16,Dominant,"water, currency",3.22,No
12,Russia-Ukraine War,Interstate War,Europe,2022,2026,Ongoing,Ukraine,9.58,23.14,13.56,Energy,18.45,10.61,24.15,9.54,15.22,102739,-43.22,78.27,50.13,184490185726,399053363761,17.32,51.12,High,"weapons, currency, water",196.55,Yes
13,Russia-Ukraine War,Interstate War,Europe,2022,2026,Ongoing,Russia,13.70,31.51,17.80,Construction,25.25,17.57,33.66,16.73,19.46,278390,-37.51,9.02,13.25,89378229024,344208650386,38.62,90.00,Low,food,185.08,Yes
14,WWII (Japan),World War,East Asia,1939,1945,Resolved,Japan,3.19,9.12,5.94,Tourism,7.55,29.17,36.14,23.17,22.33,178285,-19.26,59.39,113.10,348318868540,1018885957222,12.92,29.80,Low,"currency, weapons",19.80,Yes
15,DRC Conflict,Civil War,Africa,1996,2026,Ongoing,DRC,4.68,9.76,5.08,Tourism,7.37,23.52,28.54,16.58,18.37,11111,-18.21,114.16,205.56,456707035725,1268894731650,25.05,66.04,Low,"water, fuel, medicine",324.98,Yes
16,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,Resolved,Afghanistan,11.42,29.84,18.41,Services,26.81,13.45,27.50,9.28,20.11,20347,-29.42,65.84,35.93,19636746185,69838115333,20.81,29.73,Dominant,currency,10.44,No
17,Yemen Civil War,Civil War,Middle East,2015,2026,Ongoing,Yemen,12.24,30.25,18.01,Tourism,24.29,7.13,16.79,8.60,12.03,7560,-33.68,123.48,157.37,162155279997,565592020154,18.12,36.07,Low,"medicine, weapons, food",1.57,No
18,Russia-Ukraine War,Interstate War,Europe,2022,2026,Ongoing,Ukraine,3.30,9.68,6.37,Tourism,9.14,22.40,27.41,10.12,15.42,41586,-37.16,49.58,95.81,369210561431,1065499269545,28.35,55.44,High,"fuel, water",123.87,Yes
19,Yemen Civil War,Civil War,Middle East,2015,2026,Ongoing,Yemen,7.27,35.71,28.43,Construction,31.44,7.90,23.03,7.29,19.40,876,-36.66,22.64,28.01,237262413619,458629354674,23.02,44.13,Moderate,"fuel, water, currency",12.32,Yes

In [178]:
# s=pd.read_csv('war.csv')
# s1=s.tail(5)
# s1.to_csv('new.csv')
#保存

## 缺失值处理

In [183]:
s=pd.Series([1.2,1,'a',np.nan,None,pd.NA])#np.nan不是数字；None空；pd.NA不存在（excel的空单元格）
print(s)

0     1.2
1       1
2       a
3     NaN
4    None
5    <NA>
dtype: object

In [187]:
#查看是否是缺失值
print(s.isna())
print(s.isnull()) #一样的

0    False
1    False
2    False
3     True
4     True
5     True
dtype: bool
0    False
1    False
2    False
3     True
4     True
5     True
dtype: bool

In [189]:
s=pd.DataFrame([[1,2,3],[None,1.1,2],[1,pd.NA,'a'],[1.23,'a',np.nan]])
s

      0     1    2
0  1.00     2    3
1   NaN   1.1    2
2  1.00  <NA>    a
3  1.23     a  NaN