In [611]:
import pandas as pd
import numpy as np
#基于numpy

In [612]:
#Series：一维
#DateFrame：二维

 # Series

## 基本

In [613]:
s=pd.Series([1,2,3,4,5,6])
print(s)
#第一列索引，第二列数据

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [614]:
s=pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'])
print(s)
#index自定义索引

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [615]:
s=pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'],name='a')
print(s)
#name：描述

a    1
b    2
c    3
d    4
e    5
f    6
Name: a, dtype: int64

In [616]:
s=pd.Series({'a':1,'b':2,'c':3,'d':4,'e':5})
#可以通过字典来创建
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [617]:
s=pd.Series(s,index=['a','c'])
#在s中截取
print(s)

a    1
c    3
dtype: int64

## 属性

In [618]:
s=pd.Series([1,2,3],index=['a','b','c'],name='a')
print(s)
print(s.index) #索引
print(s.values) #元素
print(s.shape) #形状
print(s.ndim) #维度
print(s.size) #元素个数
print(s.dtype) #元素类型
print(s.name) #名字

a    1
b    2
c    3
Name: a, dtype: int64
Index(['a', 'b', 'c'], dtype='str')
[1 2 3]
(3,)
1
3
int64
a

In [619]:
s=pd.Series([1,2,3],index=['a','b','c'],name='a')
print(s)
print(s.loc['a']) #显式索引
print(s.iloc[1]) #隐式索引
print(s.loc['a':'b']) #显式切片
print(s.iloc[0:2]) #隐式切片
print(s.at['a']) #显式索引，不支持切片
print(s.iat[0]) #隐式索引，不支持切片

a    1
b    2
c    3
Name: a, dtype: int64
1
2
a    1
b    2
Name: a, dtype: int64
a    1
b    2
Name: a, dtype: int64
1
1

## 访问数据

In [620]:
s=pd.Series([1,2,3],index=['a','b','c'],name='a')
print(s['a'])  #直接访问
print(s[s<3])  #筛选

1
a    1
b    2
Name: a, dtype: int64

In [621]:
s=pd.Series([1,2,3,4,5,6,7,8,9],index=['a','b','c','d','e','f','g','h','i',],name='a')
print(s)
print(s.head()) #返回前五行
print(s.tail()) #返回后五行
#head/tail的括号中写数字则返回前几行或后几行

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
Name: a, dtype: int64
a    1
b    2
c    3
d    4
e    5
Name: a, dtype: int64
e    5
f    6
g    7
h    8
i    9
Name: a, dtype: int64

## 常用方法

In [622]:
s=pd.Series([1,2,3,4,5,6,7,8,9],index=['a','b','c','d','e','f','g','h','i',],name='a')
print(s)
print(s.isin([1,4,7]))   #判断几个值是否包含
print(s.isna())  #判断是不是缺失值
#sun()求和；mean()平均值；min()最小值；max()最大值
#var()方差；std()标准差；median()中位数；mode()众数；quantile()分位数

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
Name: a, dtype: int64
a     True
b    False
c    False
d     True
e    False
f    False
g     True
h    False
i    False
Name: a, dtype: bool
a    False
b    False
c    False
d    False
e    False
f    False
g    False
h    False
i    False
Name: a, dtype: bool

In [623]:
s=pd.Series([1,2,3,4,5,6,7,8,9],index=['a','b','c','d','e','f','g','h','i',],name='a')
print(s)
print(s.describe()) #返回常见统计数据

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
Name: a, dtype: int64
count    9.000000
mean     5.000000
std      2.738613
min      1.000000
25%      3.000000
50%      5.000000
75%      7.000000
max      9.000000
Name: a, dtype: float64

In [624]:
s=pd.Series([1,2,3,4,5,6,7,8,9],index=['a','b','c','d','e','f','g','h','i',],name='a')
print(s)
print(s.value_counts()) #每个唯一值出现次数
print(s.count())     #非缺失值数量

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
Name: a, dtype: int64
a
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
9    1
Name: count, dtype: int64
9

In [625]:
print(s)
print(s.nunique()) #唯一值个数
print(s.unique()) #返回去重后数组
print(s.keys()) #获取索引

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
Name: a, dtype: int64
9
[1 2 3 4 5 6 7 8 9]
Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='str')

In [626]:
s=pd.Series([1,1,3,5,5,6,7,7,9],index=['a','b','c','d','e','f','g','h','i',],name='a')
print(s)
print(s.drop_duplicates()) #去除重复项

a    1
b    1
c    3
d    5
e    5
f    6
g    7
h    7
i    9
Name: a, dtype: int64
a    1
c    3
d    5
f    6
g    7
i    9
Name: a, dtype: int64

In [627]:
print(s.sample())  #随机抽一个元素
print(s.sort_index()) #按索引顺序排序
print(s.sort_values()) #按值排序

h    7
Name: a, dtype: int64
a    1
b    1
c    3
d    5
e    5
f    6
g    7
h    7
i    9
Name: a, dtype: int64
a    1
b    1
c    3
d    5
e    5
f    6
g    7
h    7
i    9
Name: a, dtype: int64

# DateFrame

## 创建

In [628]:
s1=pd.Series([1,2,3,4,5,6,6,6])
s2=pd.Series([7,8,9,10,11,11,12,12])
s=pd.DataFrame({'一':s1,'二':s2})
s

   一   二
0  1   7
1  2   8
2  3   9
3  4  10
4  5  11
5  6  11
6  6  12
7  6  12

In [629]:
s=pd.DataFrame(
    {
        'name':['a','b','c'],
        'age':[10,11,12],
        'score':['1.1','1.2','1.3'],
        'bool':[True,False,True]
    },index=[1,2,3],columns=['name','score','age','bool']
)
#字典创建
#index索引；columns指定列的顺序，
s

  name score  age   bool
1    a   1.1   10   True
2    b   1.2   11  False
3    c   1.3   12   True

## 属性

In [630]:
s=pd.DataFrame(
    {
        'name':['a','b','c'],
        'age':[10,11,12],
        'score':['1.1','1.2','1.3'],
        'bool':[True,False,True]
    },index=[1,2,3],columns=['name','score','age','bool']
)
print(s.index) #行索引
print(s.columns) #列标签
print(s.values) #值
print(s.ndim) #维度
print(s.shape) #形状
print(s.dtypes) #元素类型
print(s.size) #元素个数

Index([1, 2, 3], dtype='int64')
Index(['name', 'score', 'age', 'bool'], dtype='str')
[['a' '1.1' 10 True]
 ['b' '1.2' 11 False]
 ['c' '1.3' 12 True]]
2
(3, 4)
name       str
score      str
age      int64
bool      bool
dtype: object
12

In [631]:
print(s.T) #转置
#转置会让行索引和列标签互换

          1      2     3
name      a      b     c
score   1.1    1.2   1.3
age      10     11    12
bool   True  False  True

In [632]:
print(s.loc[1])  #显式索引，获取行
print(s.iloc[1]) #隐式索引，获取行
print(s.loc[:,'name']) #显式索引，获取列
print(s.iloc[:,0])  #隐式索引，获取列

name        a
score     1.1
age        10
bool     True
Name: 1, dtype: object
name         b
score      1.2
age         11
bool     False
Name: 2, dtype: object
1    a
2    b
3    c
Name: name, dtype: str
1    a
2    b
3    c
Name: name, dtype: str

In [633]:
print(s.at[1,'name']) #显式索引，获取单个元素
print(s.iat[0,0]) #隐式索引，获取单个元素
#获取单个元素用loc也可以

a
a

## 访问数据

In [634]:
s=pd.DataFrame(
    {
        'name':['a','b','c'],
        'age':[10,11,12],
        'score':['1.1','1.2','1.3'],
        'bool':[True,False,True]
    },index=[1,2,3],columns=['name','score','age','bool']
)
s

  name score  age   bool
1    a   1.1   10   True
2    b   1.2   11  False
3    c   1.3   12   True

In [635]:
print(s['name'])#和loc和at差不多
print(s.name)

1    a
2    b
3    c
Name: name, dtype: str
1    a
2    b
3    c
Name: name, dtype: str

In [636]:
#查看部分数据
print(s.head(2)) #头两行
print(s.tail(2)) #尾两行

  name score  age   bool
1    a   1.1   10   True
2    b   1.2   11  False
  name score  age   bool
2    b   1.2   11  False
3    c   1.3   12   True

In [637]:
s.age>11  #布尔索引

1    False
2    False
3     True
Name: age, dtype: bool

In [638]:
s[s.age>11]

  name score  age  bool
3    c   1.3   12  True

In [639]:
s[(s.age>10) & (s.age<12)]

  name score  age   bool
2    b   1.2   11  False

In [640]:
s.sample(2)  #随机取，括号内写几取几条

  name score  age  bool
1    a   1.1   10  True
3    c   1.3   12  True

## 常用方法

In [641]:
#head()；tail()
s=pd.DataFrame(
    {
        'name':['a','b','c'],
        'age':[10,11,12],
        'score':['1.1','1.2','1.3'],
        'bool':[True,False,True]
    },index=[1,2,3],columns=['name','score','age','bool']
)
s

  name score  age   bool
1    a   1.1   10   True
2    b   1.2   11  False
3    c   1.3   12   True

In [642]:
print(s.isin([11])) #查看某个元素在不在
print(s.isna())  #查有没有空缺

    name  score    age   bool
1  False  False  False  False
2  False  False   True  False
3  False  False  False  False
    name  score    age   bool
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False

In [643]:
print(s.sum())  #各列求和
print(s['age'].sum()) #指定列求和

name           abc
score    1.11.21.3
age             33
bool             2
dtype: object
33

In [644]:
# print(s.age.max()) #大
# print(s.age.min()) #小
# print(s.age.mean()) #平均
# print(s.age.median())#中位
# print(s.age.mode()) #众数
# print(s.age.std()) #标准差
# print(s.age.var()) #方差
print(s.describe()) #普遍信息

        age
count   3.0
mean   11.0
std     1.0
min    10.0
25%    10.5
50%    11.0
75%    11.5
max    12.0

In [645]:
print(s.count())  #每列非缺失值个数

name     3
score    3
age      3
bool     3
dtype: int64

In [646]:
print(s.value_counts()) #每条信息出现次数
print(s.drop_duplicates()) #去重
print(s.duplicated(subset='age')) #检查是否重复(subset指定某一列

name  score  age  bool
a     1.1    10   True     1
b     1.2    11   False    1
c     1.3    12   True     1
Name: count, dtype: int64
  name score  age   bool
1    a   1.1   10   True
2    b   1.2   11  False
3    c   1.3   12   True
1    False
2    False
3    False
dtype: bool

In [647]:
print(s.replace(12,30))  #替换某个值

  name score  age   bool
1    a   1.1   10   True
2    b   1.2   11  False
3    c   1.3   30   True

In [648]:
print(s.cumsum()) #累计和

  name      score  age  bool
1    a        1.1   10     1
2   ab     1.11.2   21     1
3  abc  1.11.21.3   33     2

In [649]:
print(s.sort_index())  #按索引排序
print(s.sort_values(by=['age','score'],ascending=[True,False]))
#按值排序
#by=必须写，指定排序的列，写多个按从前往后排（前一个相同再看下一个）
#ascending=指定正逆(True从小到大，False从大到小），by写了几个这也要写几个

  name score  age   bool
1    a   1.1   10   True
2    b   1.2   11  False
3    c   1.3   12   True
  name score  age   bool
1    a   1.1   10   True
2    b   1.2   11  False
3    c   1.3   12   True

In [650]:
print(s.nlargest(2,['age'])) #取age列里最大的两个
print(s.nsmallest(2,['age'])) #取age列里最小的两个

  name score  age   bool
3    c   1.3   12   True
2    b   1.2   11  False
  name score  age   bool
1    a   1.1   10   True
2    b   1.2   11  False

# 数据分析

In [651]:
#收集，清洗，分析

## 读取输出

In [652]:
s=pd.read_csv('C:/Users/rhys1/Desktop/sj/war.csv')  #读入
s.head(20)

,Conflict_Name,Conflict_Type,Region,Start_Year,End_Year,Status,Primary_Country,Pre_War_Unemployment_%,During_War_Unemployment_%,Unemployment_Spike_Percentage_Points,...,Inflation_Rate_%,Currency_Devaluation_%,Cost_of_War_USD,Estimated_Reconstruction_Cost_USD,Informal_Economy_Size_Pre_War_%,Informal_Economy_Size_During_War_%,Black_Market_Activity_Level,Primary_Black_Market_Goods,Currency_Black_Market_Rate_Gap_%,War_Profiteering_Documented
0,WWII (Japan),World War,East Asia,1939,1945,Resolved,Japan,7.49,21.78,14.29,...,97.41,170.33,106957216228,209054555175,15.50,27.09,High,food,10.50,No
1,Israel-Hamas War,Asymmetric War,Middle East,2023,2026,Ongoing,Palestine (Gaza),8.18,23.00,14.82,...,73.68,41.97,304164881098,585915946162,11.95,34.76,Dominant,fuel,19.31,No
2,Syrian Civil War,Civil War,Middle East,2011,2026,Ongoing,Syria,12.70,36.46,23.76,...,69.35,53.91,484822729254,1666739121273,38.18,90.00,Moderate,"water, weapons, currency",298.95,No
3,WWII (Germany),World War,Europe,1939,1945,Resolved,Germany,14.06,17.83,3.77,...,36.92,48.51,71321188262,250015887113,12.24,36.42,Moderate,"currency, medicine, weapons",15.44,No
4,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,Resolved,Afghanistan,5.38,5.98,0.59,...,52.62,31.32,156180178536,361238241031,31.89,74.86,Dominant,medicine,443.61,Yes
5,WWII (Germany),World War,Europe,1939,1945,Resolved,Germany,8.67,11.50,2.84,...,13.70,9.07,16683163657,51568093097,19.43,41.10,Dominant,"fuel, currency, water",18.15,Yes
6,WWII (Japan),World War,East Asia,1939,1945,Resolved,Japan,5.99,11.26,5.27,...,93.39,122.24,403912637426,1510725456958,19.54,27.32,Moderate,"fuel, water, food",4.56,Yes
7,Israel-Hamas War,Asymmetric War,Middle East,2023,2026,Ongoing,Palestine (Gaza),8.13,42.10,33.97,...,89.58,114.50,351806460488,847527799087,39.15,90.00,Dominant,"currency, medicine",125.89,No
8,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,Resolved,Afghanistan,8.97,14.99,6.02,...,52.08,103.03,121785580484,387319415238,32.85,53.47,High,"water, fuel, food",364.11,Yes
9,Syrian Civil War,Civil War,Middle East,2011,2026,Ongoing,Syria,7.41,32.21,24.80,...,59.92,90.86,9277326635,25793126375,16.79,39.66,Dominant,"water, weapons",3.49,No
10,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,Resolved,Afghanistan,11.29,20.72,9.43,...,89.51,115.87,121684293159,210849300968,36.92,90.00,Low,"currency, medicine",316.55,No
11,WWII (Germany),World War,Europe,1939,1945,Resolved,Germany,7.07,12.47,5.40,...,93.38,131.63,5589328756,9801887666,29.91,36.16,Dominant,"water, currency",3.22,No
12,Russia-Ukraine War,Interstate War,Europe,2022,2026,Ongoing,Ukraine,9.58,23.14,13.56,...,78.27,50.13,184490185726,399053363761,17.32,51.12,High,"weapons, currency, water",196.55,Yes
13,Russia-Ukraine War,Interstate War,Europe,2022,2026,Ongoing,Russia,13.70,31.51,17.80,...,9.02,13.25,89378229024,344208650386,38.62,90.00,Low,food,185.08,Yes
14,WWII (Japan),World War,East Asia,1939,1945,Resolved,Japan,3.19,9.12,5.94,...,59.39,113.10,348318868540,1018885957222,12.92,29.80,Low,"currency, weapons",19.80,Yes
15,DRC Conflict,Civil War,Africa,1996,2026,Ongoing,DRC,4.68,9.76,5.08,...,114.16,205.56,456707035725,1268894731650,25.05,66.04,Low,"water, fuel, medicine",324.98,Yes
16,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,Resolved,Afghanistan,11.42,29.84,18.41,...,65.84,35.93,19636746185,69838115333,20.81,29.73,Dominant,currency,10.44,No
17,Yemen Civil War,Civil War,Middle East,2015,2026,Ongoing,Yemen,12.24,30.25,18.01,...,123.48,157.37,162155279997,565592020154,18.12,36.07,Low,"medicine, weapons, food",1.57,No
18,Russia-Ukraine War,Interstate War,Europe,2022,2026,Ongoing,Ukraine,3.30,9.68,6.37,...,49.58,95.81,369210561431,1065499269545,28.35,55.44,High,"fuel, water",123.87,Yes
19,Yemen Civil War,Civil War,Middle East,2015,2026,Ongoing,Yemen,7.27,35.71,28.43,...,22.64,28.01,237262413619,458629354674,23.02,44.13,Moderate,"fuel, water, currency",12.32,Yes

In [653]:
# s=pd.read_csv('war.csv')
# s1=s.tail(5)
# s1.to_csv('new.csv')
#保存

## 缺失值处理

In [654]:
s=pd.Series([1.2,1,'a',np.nan,None,pd.NA])#np.nan不是数字；None空；pd.NA不存在（excel的空单元格）
print(s)

0     1.2
1       1
2       a
3     NaN
4    None
5    <NA>
dtype: object

In [655]:
#查看是否是缺失值
print(s.isna())
print(s.isnull()) #一样的

0    False
1    False
2    False
3     True
4     True
5     True
dtype: bool
0    False
1    False
2    False
3     True
4     True
5     True
dtype: bool

In [656]:
s=pd.DataFrame(
    {'a':[1,2,3,2,5],
     'b':[1,3,None,2,3],
     'c':[np.nan,2,pd.NA,5,2],
     'd':[2,np.nan,None,pd.NA,1]})
s

   a    b     c     d
0  1  1.0   NaN     2
1  2  3.0     2   NaN
2  3  NaN  <NA>  None
3  2  2.0     5  <NA>
4  5  3.0     2     1

In [657]:
#查
print(s.isna())
print(s.isnull().sum()) #查看缺失值个数

       a      b      c      d
0  False  False   True  False
1  False  False  False   True
2  False   True   True   True
3  False  False  False   True
4  False  False  False  False
a    0
b    1
c    2
d    3
dtype: int64

In [658]:
#删
print(s.dropna()) #剔除含缺失值的行
print(s.dropna(how='all'))  #剔除所有值都缺失的行
print(s.dropna(thresh=2)) #剔除非缺失值小于两个的行
print(s.dropna(axis=1))  #写0剔除含缺失值的行，写1剔除含缺失值的列
print(s.dropna(subset=['a','b'])) #剔除a列b列中含空缺值的行

   a    b  c  d
4  5  3.0  2  1
   a    b     c     d
0  1  1.0   NaN     2
1  2  3.0     2   NaN
2  3  NaN  <NA>  None
3  2  2.0     5  <NA>
4  5  3.0     2     1
   a    b    c     d
0  1  1.0  NaN     2
1  2  3.0    2   NaN
3  2  2.0    5  <NA>
4  5  3.0    2     1
   a
0  1
1  2
2  3
3  2
4  5
   a    b    c     d
0  1  1.0  NaN     2
1  2  3.0    2   NaN
3  2  2.0    5  <NA>
4  5  3.0    2     1

In [659]:
#填
print(s.fillna({'d':99}))  #在d列的空缺值中填上99
print(s.fillna(s['c'].mean()))  #一层中括号：用c列的平均值来填充空缺值：填充表中所有空缺值
print(s.fillna(s[['c']].mean()))#两层中括号：用c列的平均值填充c列的空缺值，只填充c列的空缺值

   a    b     c   d
0  1  1.0   NaN   2
1  2  3.0     2  99
2  3  NaN  <NA>  99
3  2  2.0     5  99
4  5  3.0     2   1
   a    b    c    d
0  1  1.0  3.0    2
1  2  3.0    2  3.0
2  3  3.0  3.0  3.0
3  2  2.0    5  3.0
4  5  3.0    2    1
   a    b    c     d
0  1  1.0  3.0     2
1  2  3.0    2   NaN
2  3  NaN  3.0  None
3  2  2.0    5  <NA>
4  5  3.0    2     1

In [660]:
print(s.ffill()) #用上面的相邻值填充
print(s.bfill()) #用下面的相邻值填充

   a    b    c  d
0  1  1.0  NaN  2
1  2  3.0    2  2
2  3  3.0    2  2
3  2  2.0    5  2
4  5  3.0    2  1
   a    b  c  d
0  1  1.0  2  2
1  2  3.0  2  1
2  3  2.0  5  1
3  2  2.0  5  1
4  5  3.0  2  1

## 数据去重、类型转换

In [661]:
s=pd.DataFrame({
     'a':[1,1,3,1,5],
     'b':[2,2,3,2,3],
     'c':[1,1,5,2,2],
     'd':[2,2,4,2,1],
     })
s

   a  b  c  d
0  1  2  1  2
1  1  2  1  2
2  3  3  5  4
3  1  2  2  2
4  5  3  2  1

In [662]:
print(s.duplicated()) #标记是否重复
print(s.drop_duplicates()) #删除重复行
print(s.drop_duplicates(subset=['a']))  #指定某一列，删除重复的行（重复的默认保留第一个
print(s.drop_duplicates(subset=['a'], keep='last')) ##指定某一列，删除重复的行，重复的保留最后一个

0    False
1     True
2    False
3    False
4    False
dtype: bool
   a  b  c  d
0  1  2  1  2
2  3  3  5  4
3  1  2  2  2
4  5  3  2  1
   a  b  c  d
0  1  2  1  2
2  3  3  5  4
4  5  3  2  1
   a  b  c  d
2  3  3  5  4
3  1  2  2  2
4  5  3  2  1

In [663]:
s=pd.DataFrame({
     'a':['aaa','bbb','ccc','ddd','eee'],
     'b':[2,2,3,2,3],
     'c':[1.1,4.3,5.4,2.5,2.6],
     'd':[-2,-2,-4,-2,-1],
     'e':['a','z','z','a','a'],
     })
s

     a  b    c  d  e
0  aaa  2  1.1 -2  a
1  bbb  2  4.3 -2  z
2  ccc  3  5.4 -4  z
3  ddd  2  2.5 -2  a
4  eee  3  2.6 -1  a

In [664]:
s.dtypes

a        str
b      int64
c    float64
d      int64
e        str
dtype: object

In [665]:
s['b']=s['b'].astype('int16')  #把b这一列数据类型转换为int16
print(s.dtypes)

a        str
b      int16
c    float64
d      int64
e        str
dtype: object

In [666]:
s['e']=s['e'].astype('category')  #把e列的数据类型转换成分类
print(s.e)

0    a
1    z
2    z
3    a
4    a
Name: e, dtype: category
Categories (2, str): ['a', 'z']

In [667]:
s['e']=s['e'].map({'a':True,'z':False}) #map(字典) 从什么映射到什么
print(s.e)

0     True
1    False
2    False
3     True
4     True
Name: e, dtype: category
Categories (2, bool): [True, False]

## 数据变形

In [668]:
s=pd.DataFrame({
    'a':[1,2,3,4,5],
    'b':['a','b','c','d','e'],
    'c':[1.2,1.3,1.4,1.5,1.6],
    'd':[2,2,4,2,1],
    'e':['a','z','z','a','a'],
    'f':[1,2,3,4,5],
    'g':[2,2,4,2,1],
})
s

   a  b    c  d  e  f  g
0  1  a  1.2  2  a  1  2
1  2  b  1.3  2  z  2  2
2  3  c  1.4  4  z  3  4
3  4  d  1.5  2  a  4  2
4  5  e  1.6  1  a  5  1

In [669]:
s1=pd.melt(s,id_vars=['a','b'],var_name='aaa',value_name='num');s1
#宽变长：id_vars要固定组合的项，var_name剩下几列的名称的统称，value_name剩下几列的数据的统称

    a  b aaa  num
0   1  a   c  1.2
1   2  b   c  1.3
2   3  c   c  1.4
3   4  d   c  1.5
4   5  e   c  1.6
5   1  a   d    2
6   2  b   d    2
7   3  c   d    4
8   4  d   d    2
9   5  e   d    1
10  1  a   e    a
11  2  b   e    z
12  3  c   e    z
13  4  d   e    a
14  5  e   e    a
15  1  a   f    1
16  2  b   f    2
17  3  c   f    3
18  4  d   f    4
19  5  e   f    5
20  1  a   g    2
21  2  b   g    2
22  3  c   g    4
23  4  d   g    2
24  5  e   g    1

In [670]:
s2=pd.pivot(s1,index=['a','b'],columns='aaa',values='num');s2
#长变宽：melt的逆操作

aaa    c  d  e  f  g
a b
1 a  1.2  2  a  1  2
2 b  1.3  2  z  2  2
3 c  1.4  4  z  3  4
4 d  1.5  2  a  4  2
5 e  1.6  1  a  5  1

In [671]:
s=pd.DataFrame({
    'a':[1,2,3,4,5],
    'b':['a.d','b.g','c.q','d.f','e.g'],
    'c':[1.2,1.3,1.4,1.5,1.6],
    'd':[2,2,4,2,1],
    'e':['a','z','z','a','a'],
    'f':[1,2,3,4,5],
    'g':[2,2,4,2,1],
})
s

   a    b    c  d  e  f  g
0  1  a.d  1.2  2  a  1  2
1  2  b.g  1.3  2  z  2  2
2  3  c.q  1.4  4  z  3  4
3  4  d.f  1.5  2  a  4  2
4  5  e.g  1.6  1  a  5  1

In [672]:
s[['fir','sec']]=s['b'].str.split('.',expand=True) #分列，把b列分成两列加到s中并把列名叫fir,sec
s

   a    b    c  d  e  f  g fir sec
0  1  a.d  1.2  2  a  1  2   a   d
1  2  b.g  1.3  2  z  2  2   b   g
2  3  c.q  1.4  4  z  3  4   c   q
3  4  d.f  1.5  2  a  4  2   d   f
4  5  e.g  1.6  1  a  5  1   e   g

## 数据分箱

In [673]:
s=pd.DataFrame({
    'a':[1,2,3,4,5,6],
    'b':['a.d','b.g','c.q','d.f','e.g','s.t'],
    'c':[0.2,0.3,0.4,1.4,3.8,4.9],
    'd':[2,2,4,2,1,3],
    'e':['a','z','z','a','a','z'],
    'f':[1,2,3,4,5,6],
    'g':[2,2,4,2,1,6],
})
s

   a    b    c  d  e  f  g
0  1  a.d  0.2  2  a  1  2
1  2  b.g  0.3  2  z  2  2
2  3  c.q  0.4  4  z  3  4
3  4  d.f  1.4  2  a  4  2
4  5  e.g  3.8  1  a  5  1
5  6  s.t  4.9  3  z  6  6

In [674]:
s1=s[['b','c']]
pd.cut(s1['c'],bins=3)  #把c列按值分成两个范围（bins写几分几个均匀的区间

0    (0.195, 1.767]
1    (0.195, 1.767]
2    (0.195, 1.767]
3    (0.195, 1.767]
4      (3.333, 4.9]
5      (3.333, 4.9]
Name: c, dtype: category
Categories (3, interval[float64, right]): [(0.195, 1.767] < (1.767, 3.333] < (3.333, 4.9]]

In [675]:
s1=s[['b','c']]
pd.cut(s1['c'],bins=[0,1,2,3,4]) #列表内写不同区间的分割点

0    (0.0, 1.0]
1    (0.0, 1.0]
2    (0.0, 1.0]
3    (1.0, 2.0]
4    (3.0, 4.0]
5           NaN
Name: c, dtype: category
Categories (4, interval[int64, right]): [(0, 1] < (1, 2] < (2, 3] < (3, 4]]

In [676]:
s1=s[['b','c']]
s1['fw']=pd.cut(s1['c'],bins=[0,1,2,4],labels=['低','中','高'])
s1

     b    c   fw
0  a.d  0.2    低
1  b.g  0.3    低
2  c.q  0.4    低
3  d.f  1.4    中
4  e.g  3.8    高
5  s.t  4.9  NaN

In [677]:
s1=s[['b','c']]
pd.qcut(s1['c'],3)   #把c列按数量均分

0    (0.199, 0.367]
1    (0.199, 0.367]
2      (0.367, 2.2]
3      (0.367, 2.2]
4        (2.2, 4.9]
5        (2.2, 4.9]
Name: c, dtype: category
Categories (3, interval[float64, right]): [(0.199, 0.367] < (0.367, 2.2] < (2.2, 4.9]]

## 数据修改

In [678]:
s=pd.DataFrame({
    'a':[1,2,3,4,5,6],
    'b':['a.d','b.g','c.q','d.f','e.g','s.t'],
    'c':[0.2,0.3,0.4,1.4,3.8,4.9],
    'd':[2,2,4,2,1,3],
    'e':['a','z','z','a','a','z'],
    'f':[1,2,3,4,5,6],
    'g':[2,2,4,2,1,6],
})
s

   a    b    c  d  e  f  g
0  1  a.d  0.2  2  a  1  2
1  2  b.g  0.3  2  z  2  2
2  3  c.q  0.4  4  z  3  4
3  4  d.f  1.4  2  a  4  2
4  5  e.g  3.8  1  a  5  1
5  6  s.t  4.9  3  z  6  6

In [679]:
s.set_index('a',inplace=True);s  #把某一列设为索引,默认返回新表，加上inplace=True修改原列表

     b    c  d  e  f  g
a
1  a.d  0.2  2  a  1  2
2  b.g  0.3  2  z  2  2
3  c.q  0.4  4  z  3  4
4  d.f  1.4  2  a  4  2
5  e.g  3.8  1  a  5  1
6  s.t  4.9  3  z  6  6

In [680]:
s.reset_index(inplace=True);s  #逆向操作

   a    b    c  d  e  f  g
0  1  a.d  0.2  2  a  1  2
1  2  b.g  0.3  2  z  2  2
2  3  c.q  0.4  4  z  3  4
3  4  d.f  1.4  2  a  4  2
4  5  e.g  3.8  1  a  5  1
5  6  s.t  4.9  3  z  6  6

In [681]:
s.rename(columns={'a':'zzz'},index={0:999},inplace=True);s
#把s中a列的名字改成zzz,第0行的索引改成999
#colums列名，index行名

     zzz    b    c  d  e  f  g
999    1  a.d  0.2  2  a  1  2
1      2  b.g  0.3  2  z  2  2
2      3  c.q  0.4  4  z  3  4
3      4  d.f  1.4  2  a  4  2
4      5  e.g  3.8  1  a  5  1
5      6  s.t  4.9  3  z  6  6

## 时间数据处理

In [682]:
d=pd.Timestamp('2026-03-04 11:30')
print(d)
print(d.year)
print(d.month)
print(d.day)
print(d.hour)
print(d.minute)
print(d.second)
print(d.quarter)

2026-03-04 11:30:00
2026
3
4
11
30
0
1

In [683]:
print(d.is_month_end )
#is加year,month,day,和start,end

False

In [684]:
print(d.day_name())  #返回星期几
print(d.to_period('D'))
#转换:'Q'季度；'Y'年；'M'月；'D'天；'W'周维度
print(d.to_period('W'))

Wednesday
2026-03-04
2026-03-02/2026-03-08

In [685]:
#字符串转化为日期
print(pd.to_datetime('20260304173433'))

2026-03-04 17:34:33

In [686]:
s=pd.DataFrame({
    'a':[1,2,3,4,5],
    'date':[20250605,20250809,20260708,20240304,20251230],
})
s

   a      date
0  1  20250605
1  2  20250809
2  3  20260708
3  4  20240304
4  5  20251230

In [687]:
s['date']=s['date'].astype('str')
s['datetime']=pd.to_datetime(s['date'])
s

   a      date   datetime
0  1  20250605 2025-06-05
1  2  20250809 2025-08-09
2  3  20260708 2026-07-08
3  4  20240304 2024-03-04
4  5  20251230 2025-12-30

In [688]:
print(s.info())

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   a         5 non-null      int64
 1   date      5 non-null      str
 2   datetime  5 non-null      datetime64[us]
dtypes: datetime64[us](1), int64(1), str(1)
memory usage: 252.0 bytes
None

In [689]:
s['weekday']=s['datetime'].dt.day_name();s
#批量操作加.dt

   a      date   datetime    weekday
0  1  20250605 2025-06-05   Thursday
1  2  20250809 2025-08-09   Saturday
2  3  20260708 2026-07-08  Wednesday
3  4  20240304 2024-03-04     Monday
4  5  20251230 2025-12-30    Tuesday

In [690]:
d1=pd.Timestamp('20230927')
d2=pd.Timestamp('20260304')
print(d2-d1)

889 days 00:00:00

In [693]:
s.sort_values(['datetime'],inplace=True)
s['delta']=s['datetime']-s['datetime'][3]
s

   a      date   datetime    weekday    delta
3  4  20240304 2024-03-04     Monday   0 days
0  1  20250605 2025-06-05   Thursday 458 days
1  2  20250809 2025-08-09   Saturday 523 days
4  5  20251230 2025-12-30    Tuesday 666 days
2  3  20260708 2026-07-08  Wednesday 856 days

In [705]:
days=pd.date_range('2025-12-23',periods=6,freq='MS')
#起始日期，periods表示几个，freq表示按什么跨度取：D天；W周；ME月底；MS月初；YE年底；YS年初；
print(days)

DatetimeIndex(['2026-01-01', '2026-02-01', '2026-03-01', '2026-04-01',
               '2026-05-01', '2026-06-01'],
              dtype='datetime64[us]', freq='MS')

In [706]:
#s[['date']].resample('YS').mean()   #把date这一列按年重新采样，按平均值输出

## 分组聚合

In [717]:
#组。groupby('分组的字段')['聚合的字段'].聚合函数()
s=pd.DataFrame({
    'id':[1,1,1,2,3,4,4,5,5,6,6,7],
    'select':[100,300,200,500,400,200,300,400,450,500,200,700]
})
s

    id  select
0    1     100
1    1     300
2    1     200
3    2     500
4    3     400
5    4     200
6    4     300
7    5     400
8    5     450
9    6     500
10   6     200
11   7     700

In [718]:
s.groupby('id').groups   #查看分组

{1: [0, 1, 2], 2: [3], 3: [4], 4: [5, 6], 5: [7, 8], 6: [9, 10], 7: [11]}

In [719]:
s.groupby('id').get_group(1) #查看某个具体的分组

   id  select
0   1     100
1   1     300
2   1     200

In [755]:
s1=s.groupby('id')[['select']].mean()   #id列相同的分一组，每组查select列的平均数
s1=s1.reset_index()
s1.sort_values('select',inplace=True) #从小到大排序
s1

   id  select
0   1   200.0
3   4   250.0
5   6   350.0
2   3   400.0
4   5   425.0
1   2   500.0
6   7   700.0

In [759]:
s=pd.DataFrame({
    'id1':[1,1,1,2,3,4,4,5,5,6,6,7],
    'id2':[1,1,2,1,1,1,2,1,2,1,2,1],
    'select':[100,300,200,500,400,200,300,400,450,500,200,700],
})
s

    id1  id2  select
0     1    1     100
1     1    1     300
2     1    2     200
3     2    1     500
4     3    1     400
5     4    1     200
6     4    2     300
7     5    1     400
8     5    2     450
9     6    1     500
10    6    2     200
11    7    1     700

In [775]:
s1=s.groupby(['id1','id2'])[['select']].mean()
s1['select']=s1['select'].round(1)   #保留一位小数
s1.sort_values('select',inplace=True)
s1

         select
id1 id2
1   1     200.0
    2     200.0
4   1     200.0
6   2     200.0
4   2     300.0
5   1     400.0
3   1     400.0
5   2     450.0
2   1     500.0
6   1     500.0
7   1     700.0